version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: npm start
  
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

volumes:
  db_data: